### ISSUE TITLE
Error with PayPal payment in test application

### ISSUE THREAD

**Issue by jdimov** [braintree/braintree_aspnet_example#14]
### General information

* Environment: Sandbox
* Language, language version, and OS: .Net on Windows 10

### Issue description

I set up my braintree sandbox account and link my PayPal sandbox account within. Refresh your test application and PayPal button go to live, but when I click it have error:
_{"error":{"errorName":"AUTHORIZATION_ERROR","errorMessage":"Authorization error --- REFUSED_MARK_REF_TXN_NOT_ENABLED:This merchant account is not permitted to create Merchant Initiated Billing Agreement","debugId":"fba7a82adb8cf, fba7a82adb8cf","paypalHttpStatus":403}}_

**Comment by crookedneighbor** [comment]
Please contact our support team (https://developers.braintreepayments.com/forms/contact) with your public merchant id and the email you use to manage your PayPal sandbox. This is most likely a problem with your PayPal sandbox account not being set up correctly and not a problem with this repo. They will be able to help you.

**Comment by trongrg** [comment]
I believe that this is an issue with this repo.

When you change the config "Braintree Account Details -> Environment" to sandbox, it automatically fills in the credentials. The problem is that those credentials are incorrect, and doesn't allow paypal express checkout, with the above message.

So this is your sandbox account having the problems not being set up correctly
