### ISSUE TITLE
The Form doesn't send nonce value back to the server

### ISSUE THREAD

**Issue by khanrafay** [braintree/braintree_aspnet_example#28]
### General information

Sandbox
C# Windows 

### Issue description

The form doesn't send the value of nonce to server side.
It does post back but without any nonce value.

I tried to make a hidden text box and set the value from js but it still returns null value.

**Comment by crookedneighbor** [comment]
The integration tests pass https://github.com/braintree/braintree_aspnet_example/blob/e876f87a8e606ad224e1639d04442a36ce5069c1/BraintreeASPExampleTests/integration/CheckoutsControllerIntegrationTest.cs#L86-L196

Is it possible that you are using a different version of aspnet than is used in this example and the [way to pull out the values from the form](https://github.com/braintree/braintree_aspnet_example/blob/e876f87a8e606ad224e1639d04442a36ce5069c1/BraintreeASPExample/Controllers/CheckoutsController.cs#L47) has changed?

**Comment by khanrafay** [comment]
Thanks for replying, i tried changing it form formCollection to Request[#nonce] but still it's getting null.
PFA file.
![untitled](https://user-images.githubusercontent.com/13959906/53886733-7b2bd480-4042-11e9-8ebb-6d4cf127c4f1.png)

**Comment by crookedneighbor** [comment]
Okay, you're not using this example app then. In the future, please reach out to our support team. https://help.braintreepayments.com/

Your issue is simply that you're not preventing the default behavior of the submit button, which is to submit the form. You can see from this example that we attach the event listener to the form itself and prevent the default behavior: https://github.com/braintree/braintree_aspnet_example/blob/e876f87a8e606ad224e1639d04442a36ce5069c1/BraintreeASPExample/Views/Checkouts/New.cshtml#L46-L47

The same thing should work for you submit button.

If you don't do that, the page doesn't know _not_ to submit the form, and will submit before the card can be tokenized and insert the nonce. You definitely want to target the name of the input, not the id, when pulling the data on your server.

**Comment by khanrafay** [comment]
Thanks but this one was for drop in, and i am currently working on hosted fields.

**Comment by crookedneighbor** [comment]
The concept is the same. Web Drop-in is built using Hosted Fields for the credit card form.

If you need additional help, please contact our support team. They can guide you through any issues with your specific integration. help.braintreepayments.com
